### ISSUE TITLE
Assets Issue: CSS Not Loading Properly

### ISSUE THREAD

**Issue by FrugalGeek** [nunopress/grav-theme-alpha#1]
Just installed Alpha on a fresh Grav install using bin/gpm method. CSS didn't load properly for me. Upon inspecting received these errors:

```
http://(localURL)/user/themes/alphaassets/css/style-wide.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(localURL)/user/themes/alphaassets/css/style.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(localURL)/user/themes/alphaassets/css/style-wide.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

Seems like the `/` between alpha and assets directory is missing.

**Comment by namaless** [comment]
Fixed and release new version.

Thanks for info, i check the other html5up theme i think all have the same problem :)
